### ISSUE TITLE
University ID card starting characters

### ISSUE THREAD

**Issue by kcollignon** [CarlRaymond/jquery.cardswipe#30]
Hi there,

Based on #24 I can successfully parse cards with the `generic` parser that look something like:

`;0001234567?`

However, it does not appear that it parses cards where the beginning starts with `%` but is not followed by a letter. For example, raw output in vim outputs something like:

`%1034567^SMITH/MIKE^987654321?;987654321` or `%62772061397873^00000000^X?`

Am I missing something here or do I need to alter any configuration to get cards that start with `% + number` to work?

**Comment by CarlRaymond** [comment]
This one you can't fix with configuration; you'll have to modify the code a bit. On line 231, the state machine switched from PENDING to READING only on a letter. % followed by a non-letter won't work. You could modify that line to:

    if ((e.which >= 65 && e.which <= 90) || (e.which >= 97 && e.which <= 122) || (e.which >= 48 && e.which <= 57)) {

Then it will switch to the READING state on an upper- or lower-case letter or digit, and continue scanning.

I looked closely at the generic regex on line 44, and it's not going to match your first case, since it expects a trailing ? character.  You could write a modified parser with a different regex.

Thanks for the additional scan samples. I can only work with the cards I have available to me, so it's not surprising it misses some cards.  If the above works, I'll incorporate it into the code.

**Comment by kcollignon** [comment]
@CarlRaymond thank you so much for this information. This fix seemed to work great!

**Comment by CarlRaymond** [comment]
Very good. I'll update the code to allow % followed by digit.
